### ISSUE TITLE
v2.0.0 development

### ISSUE THREAD

**Issue by morrisallison** [morrisallison/event-station#71]
### Todo

- [x] Update TypeScript
- [x] Add support for generics to map event names to event payloads
- [x] Replace all tooling with Bun
    - Node.js, uglifyjs, mocha, nyc, etc.
- [x] Convert all LiveScript tests into TypeScript
- [x] Stop referencing globals, i.e. `window`, `document`, `global` etc.
    - If necessary, use `globalThis` instead
- [x] Drop support for injecting custom `Promise` constructors
- [x] Drop support for Rx injection
     - Instead, just make it easy to compose with Rx, and document how to do it
- [x] Drop support for Bower releases
